#' Find the Linear Point in a LOESS Fit
#'
#' This function identifies a point in a LOESS (Locally Estimated Scatterplot Smoothing) fit where the curve transitions from a peak to an approximately linear region. The function is useful in cases where it is important to detect the onset of linear behavior in a smoothed curve, such as in quality control or trend analysis.
#'
#' @importFrom stats lm coef
#' @param mean_values A numeric vector representing the mean values of the input data. These values correspond to the x-axis values used in the LOESS fit.
#' @param cv_values A numeric vector representing the coefficient of variation (CV) values of the input data. These values correspond to the y-axis values used in the LOESS fit.
#' @param lowess_fit A list containing the results of the LOESS fit, typically generated by the `lowess` function in R. The list should have elements `x` (mean values) and `y` (predicted CV values).
#' @param window_size An integer specifying the number of points to consider in each sliding window when calculating local slopes. The default is 5.
#'
#' @return A numeric value representing the mean value at the point where the LOESS curve becomes approximately linear after the peak. If no such point is found, the function returns `NULL`.
#'
#' @details
#' The function first identifies the peak of the LOESS curve (the maximum predicted value). It then examines the region after the peak to detect where the curve transitions to a linear slope by fitting small linear models across a sliding window of points. The point at which the slope stabilizes is considered the onset of linearity.
#'
#' @keywords internal
#'
find_linear_point <- function(mean_values, cv_values, lowess.f, window_size = 50) {

  # Perform LOESS smoothing on the coefficient of variation (CV) values
  total.lowess <- lowess(cv_values ~ mean_values, f = lowess.f)

  # Extract predicted values (LOESS y-values) and corresponding means (LOESS x-values)
  loess_pred <- total.lowess$y  # Predicted values from the LOESS fit
  loess_mean <- total.lowess$x   # Corresponding mean values from the LOESS fit

  # Ensure LOESS predictions and means have the same length
  if (length(loess_pred) != length(loess_mean)) {
    stop("LOESS predictions and means do not have the same length.")
  }

  # Find the index of the peak value in the LOESS predictions
  peak_index <- which.max(loess_pred)

  # Ensure the peak index is valid and not at the last position
  if (is.na(peak_index) || peak_index == length(loess_pred)) {
    warning("Peak is at the last point or index is NA, unable to analyze the post-peak region.")
    return(NULL)
  }

  # Consider only the points after the peak in the LOESS predictions
  post_peak_mean <- loess_mean[(peak_index + 1):length(loess_mean)]  # Means after the peak
  post_peak_loess_pred <- loess_pred[(peak_index + 1):length(loess_pred)]  # Predictions after the peak

  # Ensure there are enough points in the post-peak region
  if (length(post_peak_mean) < window_size) {
    warning("Not enough points to analyze the post-peak region.")
    return(NULL)
  }

  # Calculate local slopes (linear fits) across a sliding window
  slopes <- sapply(1:(length(post_peak_mean) - window_size + 1), function(i) {
    fit <- lm(post_peak_loess_pred[i:(i + window_size - 1)] ~ post_peak_mean[i:(i + window_size - 1)])
    coef(fit)[2]  # Return the slope of the linear fit
  })

  # Find where the slope becomes more consistent (closer to linear relationship)
  slopes_diff <- abs(diff(slopes))

  # Find the first point where the slope change is minimized
  linear_point_index <- which(slopes_diff == min(slopes_diff))[1]

  if (!is.na(linear_point_index)) {
    linear_mean <- post_peak_mean[linear_point_index + floor(window_size / 2)]
    linear_cv <- cv_values[which(mean_values == linear_mean)]

    # Check if the linear mean exceeds the threshold
    if (linear_mean > 5) {
      warning("Selected noise threshold >5, manually inspect the data structure using the plotNoiseCorrection() function.")
    }

    return(linear_mean)
  } else {
    warning("No clear linear region found beyond the peak.")
    return(NULL)
  }
}
